services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis-stack
    develop:
      watch:
        - action: sync
          path: ./
          target: /
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  redis-stack:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
volumes:
  redis_data: